"""first migration

Revision ID: 15a12c7979f1
Revises: 
Create Date: 2025-04-08 18:08:11.280853

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a12c7979f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_details_billable_icd_code'), 'details_billable', ['icd_code'], unique=False)
    op.create_table('details_non_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_details_non_billable_icd_code'), 'details_non_billable', ['icd_code'], unique=False)
    op.create_table('pagination_billable',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagination_non_billable',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_billable_icd_code'), 'urls_billable', ['icd_code'], unique=False)
    op.create_table('urls_non_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_non_billable_icd_code'), 'urls_non_billable', ['icd_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_non_billable_icd_code'), table_name='urls_non_billable')
    op.drop_table('urls_non_billable')
    op.drop_index(op.f('ix_urls_billable_icd_code'), table_name='urls_billable')
    op.drop_table('urls_billable')
    op.drop_table('pagination_non_billable')
    op.drop_table('pagination_billable')
    op.drop_index(op.f('ix_details_non_billable_icd_code'), table_name='details_non_billable')
    op.drop_table('details_non_billable')
    op.drop_index(op.f('ix_details_billable_icd_code'), table_name='details_billable')
    op.drop_table('details_billable')
    # ### end Alembic commands ###
