"""first migration

Revision ID: 1d2f1020cdf9
Revises: 
Create Date: 2025-05-18 15:54:51.532897

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1d2f1020cdf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagination_billable',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pagination_non_billable',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('urls_billable',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('icd_code', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_urls_billable_icd_code'), 'urls_billable', ['icd_code'], unique=False)
    op.create_table('urls_non_billable',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('icd_code', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_urls_non_billable_icd_code'), 'urls_non_billable', ['icd_code'], unique=False)
    op.create_table('history_billable',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('icd_code', sa.String(), nullable=False),
                    sa.Column('code_history', sa.String(), nullable=False),
                    sa.Column('url_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['url_id'], ['urls_billable.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url_id')
                    )
    op.create_index(op.f('ix_history_billable_icd_code'), 'history_billable', ['icd_code'], unique=False)
    op.create_table('history_non_billable',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
                    sa.Column('icd_code', sa.String(), nullable=False),
                    sa.Column('code_history', sa.String(), nullable=False),
                    sa.Column('url_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['url_id'], ['urls_non_billable.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url_id')
                    )
    op.create_index(op.f('ix_history_non_billable_icd_code'), 'history_non_billable', ['icd_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_non_billable_icd_code'), table_name='history_non_billable')
    op.drop_table('history_non_billable')
    op.drop_index(op.f('ix_history_billable_icd_code'), table_name='history_billable')
    op.drop_table('history_billable')
    op.drop_index(op.f('ix_urls_non_billable_icd_code'), table_name='urls_non_billable')
    op.drop_table('urls_non_billable')
    op.drop_index(op.f('ix_urls_billable_icd_code'), table_name='urls_billable')
    op.drop_table('urls_billable')
    op.drop_table('pagination_non_billable')
    op.drop_table('pagination_billable')
    # ### end Alembic commands ###
