"""add url_id set not null

Revision ID: 3e961ec66213
Revises: a733333b7808
Create Date: 2025-05-08 12:18:16.399288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e961ec66213'
down_revision: Union[str, None] = 'a733333b7808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_billable', schema=None) as batch_op:
        batch_op.execute("""
            UPDATE history_billable
            SET url_id = (
                SELECT urls_billable.id
                FROM urls_billable
                WHERE urls_billable.icd_code = history_billable.icd_code
            )
        """)

    with op.batch_alter_table('history_billable', schema=None) as batch_op:
        batch_op.alter_column('url_id', existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table('history_non_billable', schema=None) as batch_op:
        batch_op.execute("""
            UPDATE history_non_billable
            SET url_id = (
                SELECT urls_non_billable.id
                FROM urls_non_billable
                WHERE urls_non_billable.icd_code = history_non_billable.icd_code
            )
        """)

    with op.batch_alter_table('history_non_billable', schema=None) as batch_op:
        batch_op.alter_column('url_id', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_billable', schema=None) as batch_op:
        batch_op.alter_column(
            'url_id',
            existing_type=sa.Integer(),
            nullable=True
        )

    with op.batch_alter_table('history_non_billable', schema=None) as batch_op:
        batch_op.alter_column(
            'url_id',
            existing_type=sa.Integer(),
            nullable=True
        )

    op.execute("UPDATE history_billable SET url_id = NULL")
    op.execute("UPDATE history_non_billable SET url_id = NULL")

    # ### end Alembic commands ###
