"""add url_id to history

Revision ID: a733333b7808
Revises: 84968c2f56ce
Create Date: 2025-05-08 11:24:06.261937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a733333b7808'
down_revision: Union[str, None] = '84968c2f56ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_billable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_history_billable_url_id', ['url_id'])
        batch_op.create_foreign_key('fk_history_billable_url_id', 'urls_billable', ['url_id'], ['id'])

    with op.batch_alter_table('history_non_billable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_history_non_billable_url_id', ['url_id'])
        batch_op.create_foreign_key('fk_history_non_billable_url_id', 'urls_non_billable', ['url_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_non_billable', schema=None) as batch_op:
        batch_op.drop_constraint('fk_history_non_billable_url_id', type_='foreignkey')
        batch_op.drop_constraint('uq_history_non_billable_url_id', 'history_non_billable', type_='unique')
        batch_op.drop_column('url_id')

    with op.batch_alter_table('history_billable', schema=None) as batch_op:
        batch_op.drop_constraint('fk_history_billable_url_id', type_='foreignkey')
        batch_op.drop_constraint('uq_history_billable_url_id', 'history_billable', type_='unique')
        batch_op.drop_column('url_id')

    # ### end Alembic commands ###
