"""add history JSONB

Revision ID: b1ee4faf1610
Revises: 1d2f1020cdf9
Create Date: 2025-05-20 15:29:16.287671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1ee4faf1610'
down_revision: Union[str, None] = '1d2f1020cdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_billable', sa.Column('history', postgresql.JSONB(astext_type=sa.Text())))
    op.add_column('history_non_billable', sa.Column('history', postgresql.JSONB(astext_type=sa.Text())))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_non_billable', 'history')
    op.drop_column('history_billable', 'history')
    # ### end Alembic commands ###
