"""first_migration

Revision ID: b5517a803125
Revises: 
Create Date: 2025-04-07 23:52:39.486581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5517a803125'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_non_billable_icd_code', table_name='url_non_billable')
    op.drop_table('url_non_billable')
    op.drop_index('ix_detail_billable_icd_code', table_name='detail_billable')
    op.drop_table('detail_billable')
    op.drop_index('ix_detail_non_billable_icd_code', table_name='detail_non_billable')
    op.drop_table('detail_non_billable')
    op.drop_index('ix_url_billable_icd_code', table_name='url_billable')
    op.drop_table('url_billable')
    op.drop_table('pagination_non_billable')
    op.drop_table('pagination_billable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagination_billable',
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagination_non_billable',
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_billable',
    sa.Column('icd_code', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_url_billable_icd_code', 'url_billable', ['icd_code'], unique=False)
    op.create_table('detail_non_billable',
    sa.Column('icd_code', sa.VARCHAR(), nullable=False),
    sa.Column('detail', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detail_non_billable_icd_code', 'detail_non_billable', ['icd_code'], unique=False)
    op.create_table('detail_billable',
    sa.Column('icd_code', sa.VARCHAR(), nullable=False),
    sa.Column('detail', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detail_billable_icd_code', 'detail_billable', ['icd_code'], unique=False)
    op.create_table('url_non_billable',
    sa.Column('icd_code', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_url_non_billable_icd_code', 'url_non_billable', ['icd_code'], unique=False)
    # ### end Alembic commands ###
