"""first revision

Revision ID: bd6cb36d39dc
Revises: 
Create Date: 2025-04-08 16:26:19.226353

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6cb36d39dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_billable_icd_code'), 'detail_billable', ['icd_code'], unique=False)
    op.create_table('detail_non_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_non_billable_icd_code'), 'detail_non_billable', ['icd_code'], unique=False)
    op.create_table('pagination_billable',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagination_non_billable',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_billable_icd_code'), 'url_billable', ['icd_code'], unique=False)
    op.create_table('url_non_billable',
    sa.Column('icd_code', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_non_billable_icd_code'), 'url_non_billable', ['icd_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_non_billable_icd_code'), table_name='url_non_billable')
    op.drop_table('url_non_billable')
    op.drop_index(op.f('ix_url_billable_icd_code'), table_name='url_billable')
    op.drop_table('url_billable')
    op.drop_table('pagination_non_billable')
    op.drop_table('pagination_billable')
    op.drop_index(op.f('ix_detail_non_billable_icd_code'), table_name='detail_non_billable')
    op.drop_table('detail_non_billable')
    op.drop_index(op.f('ix_detail_billable_icd_code'), table_name='detail_billable')
    op.drop_table('detail_billable')
    # ### end Alembic commands ###
