"""delete code_history column

Revision ID: e5107fdcfb9f
Revises: b1ee4faf1610
Create Date: 2025-05-21 19:41:09.556609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5107fdcfb9f'
down_revision: Union[str, None] = 'b1ee4faf1610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history_billable", "code_history")
    op.drop_column("history_non_billable", "code_history")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history_billable",
        sa.Column("code_history", sa.String(), nullable=True)
    )
    op.add_column(
        "history_non_billable",
        sa.Column("code_history", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###
